### ISSUE TITLE
Neo4j wont start

### ISSUE THREAD

**Issue by Praniyendeev** [DozerDB/dozerdb-plugin#2]
Hi all,

Thanks for the amazing plugin.

I am unable to start my neo4j instance with dozerdb plugin.
Some relevant info:
1. My class_path prefix was also set as directed to:
               `$CLASSPATH_PREFIX=$HOME/neo4j-community-5.12.0/lib/dozerdb-plugin-5.12.0.0-alpha.1.jar`
2.I have multiple jdks in my system, but i have set the proper one(17.0.2)
               `$JAVA_HOME=$HOME/jdk-17.0.2`
                `export PATH=$JAVA_HOME/bin:$PATH`

When running the `./neo4j console` command i get the following error:

```
Directories in use:
home:         $HOME/neo4j-community-5.12.0
config:       $HOME/neo4j-community-5.12.0/conf
logs:         $HOME/neo4j-community-5.12.0/logs
plugins:      $HOME/neo4j-community-5.12.0/plugins
import:       $HOME/neo4j-community-5.12.0/import
data:         $HOME/neo4j-community-5.12.0/data
certificates: $HOME/neo4j-community-5.12.0/certificates
licenses:     $HOME/neo4j-community-5.12.0/licenses
run:          $HOME/neo4j-community-5.12.0/run
Starting Neo4j.
2023-10-15 19:43:32.348+0000 INFO  Logging config in use: File '$HOME/neo4j-community-5.12.0/conf/user-logs.xml'
2023-10-15 19:43:32.369+0000 INFO  Starting...
2023-10-15 19:43:32.370+0000 INFO  

*****************************************************************************
 *********************** Enhanced By DozerDB Plugin ***********************
*****************************************************************************


2023-10-15 19:43:33.462+0000 INFO  This instance is ServerId{2f56e106} (2f56e106-9b6b-4299-b89e-a2c13dfc47f2)
2023-10-15 19:43:34.315+0000 INFO  ======== Neo4j 5.12.0 ========
2023-10-15 19:44:15.411+0000 ERROR Failed to start Neo4j on localhost:7474.
java.lang.RuntimeException: Error starting Neo4j database server at $HOME/neo4j-community-5.12.0/data/databases
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:272) ~[neo4j-5.12.0.jar:5.12.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:208) ~[neo4j-5.12.0.jar:5.12.0]
        at org.neo4j.server.DozerDbBootstrapper.createNeo(DozerDbBootstrapper.java:46) ~[dozerdb-plugin-5.12.0.0-alpha.1.jar:?]
        at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:187) [neo4j-5.12.0.jar:?]
        at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.12.0.jar:?]
        at org.neo4j.server.DozerDbEntryPoint.main(DozerDbEntryPoint.java:48) [dozerdb-plugin-5.12.0.0-alpha.1.jar:?]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.dbms.database.DefaultSystemGraphInitializer@5d0b0cb9' was successfully initialized, but failed to start. Please see the attached cause exception "Transaction logs are missing and recovery is not possible.".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:365) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.12.0.jar:5.12.0]
        ... 5 more
Caused by: org.neo4j.graphdb.DatabaseShutdownException: This database is shutdown.
        at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.assertDatabaseAvailable(DatabaseAvailabilityGuard.java:154) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginKernelTransaction(GraphDatabaseFacade.java:148) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransactionInternal(GraphDatabaseFacade.java:117) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTransaction(GraphDatabaseFacade.java:89) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:113) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:107) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTransaction(GraphDatabaseTransactions.java:102) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.impl.factory.GraphDatabaseTransactions.beginTx(GraphDatabaseTransactions.java:93) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.dbms.database.SystemGraphComponents.initializeSystemGraph(SystemGraphComponents.java:83) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.dbms.database.DefaultSystemGraphInitializer.initializeSystemGraph(DefaultSystemGraphInitializer.java:38) ~[neo4j-5.12.0.jar:5.12.0]
        at org.neo4j.dbms.database.SystemGraphInitializer.start(SystemGraphInitializer.java:27) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:348) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.12.0.jar:5.12.0]
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.recovery.Recovery$MissingTransactionLogsCheck@6654ca0d' failed to initialize. Please see the attached cause exception "Transaction logs are missing and recovery is not possible.".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:335) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:86) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.recovery.Recovery.performRecovery(Recovery.java:735) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.recovery.Recovery.performRecovery(Recovery.java:443) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.database.Database.specificStart(Database.java:423) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.database.AbstractDatabase.start(AbstractDatabase.java:160) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:113) ~[dozerdb-plugin-5.12.0.0-alpha.1.jar:5.12.0]
        at org.neo4j.dbms.database.MultiDatabaseLifecycleService$SystemDatabaseStarter.start(MultiDatabaseLifecycleService.java:141) ~[dozerdb-plugin-5.12.0.0-alpha.1.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:348) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.12.0.jar:5.12.0]
        ... 5 more
Caused by: java.lang.RuntimeException: Transaction logs are missing and recovery is not possible.
        at org.neo4j.kernel.recovery.Recovery$MissingTransactionLogsCheck.checkForMissingLogFiles(Recovery.java:997) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.recovery.Recovery$MissingTransactionLogsCheck.init(Recovery.java:983) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:318) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:57) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:86) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.recovery.Recovery.performRecovery(Recovery.java:735) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.recovery.Recovery.performRecovery(Recovery.java:443) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.database.Database.specificStart(Database.java:423) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.database.AbstractDatabase.start(AbstractDatabase.java:160) ~[neo4j-kernel-5.12.0.jar:5.12.0]
        at org.neo4j.dbms.database.MultiDatabaseManager.startDatabase(MultiDatabaseManager.java:113) ~[dozerdb-plugin-5.12.0.0-alpha.1.jar:5.12.0]
        at org.neo4j.dbms.database.MultiDatabaseLifecycleService$SystemDatabaseStarter.start(MultiDatabaseLifecycleService.java:141) ~[dozerdb-plugin-5.12.0.0-alpha.1.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:348) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:92) ~[neo4j-common-5.12.0.jar:5.12.0]
        at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:263) ~[neo4j-5.12.0.jar:5.12.0]
        ... 5 more
2023-10-15 19:44:15.413+0000 INFO  Neo4j Server shutdown initiated by request
2023-10-15 19:44:15.414+0000 INFO  Stopped.
Neo4j web server failed to start. See log for more info.
Run with '--verbose' for a more detailed error message.
```

Thank you!

**Comment by jmsuhy** [comment]
It sounds like you had a data directory that was from a previous version of Neo4j that needed to be updated, etc.   What was your resolution?

**Comment by Praniyendeev** [comment]
Exactly, I had to delete the previous installation of neo4j.
