### ISSUE TITLE
Error Caused by: java.lang.ClassNotFoundException: com.neo4j.metrics.MetricsManager

### ISSUE THREAD

**Issue by awhillas** [DozerDB/dozerdb-plugin#22]
This is what I get when I run this in a docker compose?
```yaml
version: "3"
services:

  dozerdb:
    container_name: neo4j
    image: graphstack/dozerdb:5.22.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo4j_password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted='*'
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/import:/var/lib/neo4j/import
      - ./data/neo4j/plugins:/plugins
 ```
Full stack dump:
```
neo4j             | 2024-08-12 04:08:13.767+0000 INFO  GDS compatibility: for Neo4j 5.16 -- not available, for Neo4j 5.17 -- not available, for Neo4j 5.18 -- not available, for Neo4j 5.19 -- not available, for Neo4j 5.20 -- not available, for Neo4j 5.21 -- not available, for Neo4j 5.22 -- available, selected: Neo4j 5.22
neo4j             | 2024-08-12 04:08:13.776+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
neo4j             | java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
neo4j             |     at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:280) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:215) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.server.DozerDbBootstrapper.createNeo(DozerDbBootstrapper.java:46) ~[dozerdb-core-5.22.0-1.0.0-alpha.1.jar:5.22.0-1.0.0-alpha.1]
neo4j             |     at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:184) [neo4j-5.22.0.jar:5.22.0-1.0.0-alpha.1]
neo4j             |     at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.22.0.jar:5.22.0-1.0.0-alpha.1]
neo4j             |     at org.neo4j.server.DozerDbEntryPoint.main(DozerDbEntryPoint.java:48) [dozerdb-core-5.22.0-1.0.0-alpha.1.jar:5.22.0-1.0.0-alpha.1]
neo4j             | Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter@2d9de284' failed to initialize. Please see the attached cause exception "com.neo4j.metrics.MetricsManager".
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:334) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:72) ~[neo4j-kernel-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |     ... 5 more
neo4j             | Caused by: java.lang.NoClassDefFoundError: com/neo4j/metrics/MetricsManager
neo4j             |     at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.getMetricsRegister(GdsMetricsExtension.java:106) ~[graph-data-science.jar:?]
neo4j             |     at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.init(GdsMetricsExtension.java:79) ~[graph-data-science.jar:?]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:72) ~[neo4j-kernel-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |     ... 5 more
neo4j             |     Suppressed: org.neo4j.kernel.lifecycle.LifecycleException: Exception during graceful attempt to shutdown partially initialized component. Please use non suppressed exception to see original component failure.
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:324) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:72) ~[neo4j-kernel-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:215) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |             at org.neo4j.server.DozerDbBootstrapper.createNeo(DozerDbBootstrapper.java:46) ~[dozerdb-core-5.22.0-1.0.0-alpha.1.jar:5.22.0-1.0.0-alpha.1]
neo4j             |             at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:184) [neo4j-5.22.0.jar:5.22.0-1.0.0-alpha.1]
neo4j             |             at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.22.0.jar:5.22.0-1.0.0-alpha.1]
neo4j             |             at org.neo4j.server.DozerDbEntryPoint.main(DozerDbEntryPoint.java:48) [dozerdb-core-5.22.0-1.0.0-alpha.1.jar:5.22.0-1.0.0-alpha.1]
neo4j             |     Caused by: java.lang.NoClassDefFoundError: com/neo4j/metrics/MetricsManager
neo4j             |             at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.getMetricsRegister(GdsMetricsExtension.java:106) ~[graph-data-science.jar:?]
neo4j             |             at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.shutdown(GdsMetricsExtension.java:98) ~[graph-data-science.jar:?]
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:322) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             ... 11 more
neo4j             |     Caused by: java.lang.ClassNotFoundException: com.neo4j.metrics.MetricsManager
neo4j             |             at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.getMetricsRegister(GdsMetricsExtension.java:106) ~[graph-data-science.jar:?]
neo4j             |             at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.shutdown(GdsMetricsExtension.java:98) ~[graph-data-science.jar:?]
neo4j             |             at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:322) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |             ... 11 more
neo4j             | Caused by: java.lang.ClassNotFoundException: com.neo4j.metrics.MetricsManager
neo4j             |     at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
neo4j             |     at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
neo4j             |     at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
neo4j             |     at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.getMetricsRegister(GdsMetricsExtension.java:106) ~[graph-data-science.jar:?]
neo4j             |     at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.init(GdsMetricsExtension.java:79) ~[graph-data-science.jar:?]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:72) ~[neo4j-kernel-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]
neo4j             |     at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]
neo4j             |     ... 5 more
neo4j             | 2024-08-12 04:08:13.782+0000 INFO  Neo4j Server shutdown initiated by request
neo4j             | 2024-08-12 04:08:13.782+0000 INFO  Stopped.
neo4j exited with code 1
```
?

**Comment by awhillas** [comment]
Same thing when i run `graphstack/dozerdb:5.22.0.0-alpha.1`?

**Comment by jmsuhy** [comment]
Using the provided docker-compose file content you provided - I did not get this issue.
Do you happen to have some enterprise or commercial plugin in your ./data/neo4j/plugins folder?

Please let me know the files that are in ./data/neo4j/plugins and I can help you troubleshoot.

**Comment by awhillas** [comment]
yeah, turns out it was the plugin compatibility thing. Solved it. Thanks for getting back to me!

**Comment by muddassir-lateef** [comment]
@awhillas I am having the same issue.can you lemme know what version worked for you?
