### ISSUE TITLE
Error: compat is required

### ISSUE THREAD

**Issue by lucifermorningstar1305** [DozerDB/dozerdb-plugin#31]
Thanks for this amazing plugin, unfortunately I tried the docker command that you have mentioned but with `graph-data-science` being added into the plugin list and this is the error that I am getting:

```
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases

	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:280) ~[neo4j-5.22.0.jar:5.22.0]

	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:215) ~[neo4j-5.22.0.jar:5.22.0]

	at org.neo4j.server.DozerDbBootstrapper.createNeo(DozerDbBootstrapper.java:46) ~[dozerdb-core-5.22.0-1.0.0-alpha.1.jar:5.22.0-1.0.0-alpha.1]

	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:184) [neo4j-5.22.0.jar:5.22.0-1.0.0-alpha.1]

	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:99) [neo4j-5.22.0.jar:5.22.0-1.0.0-alpha.1]

	at org.neo4j.server.DozerDbEntryPoint.main(DozerDbEntryPoint.java:48) [dozerdb-core-5.22.0-1.0.0-alpha.1.jar:5.22.0-1.0.0-alpha.1]

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalExtensions@c446b14' failed to initialize. Please see the attached cause exception "compat is required".

	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:334) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]

	... 5 more

Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:PackageVerificationExtension[gds.internal.verification] because of an unanticipated error: 'compat is required'.

	at org.neo4j.kernel.extension.ExtensionFailureStrategies.wrap(ExtensionFailureStrategies.java:56) ~[neo4j-kernel-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.extension.ExtensionFailureStrategies$1.handle(ExtensionFailureStrategies.java:68) ~[neo4j-kernel-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:68) ~[neo4j-kernel-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]

	... 5 more

Caused by: java.lang.NullPointerException: compat is required

	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]

	at org.neo4j.gds.compat.ProcedureSignatureBuilder.build(ProcedureSignatureBuilder.java:127) ~[open-gds-2.8.0-alpha01.jar:?]

	at com.neo4j.gds.configuration.PackageVerificationProcedure.signature(PackageVerificationProcedure.java:46) ~[graph-data-science.jar:?]

	at org.neo4j.gds.compat.CallableProcedureImpl.signature(CallableProcedureImpl.java:41) ~[open-gds-2.8.0-alpha01.jar:?]

	at org.neo4j.procedure.impl.ProcedureRegistry.register(ProcedureRegistry.java:78) ~[neo4j-procedure-5.22.0.jar:5.22.0]

	at org.neo4j.procedure.impl.GlobalProceduresRegistry.register(GlobalProceduresRegistry.java:106) ~[neo4j-procedure-5.22.0.jar:5.22.0]

	at com.neo4j.gds.configuration.PackageVerificationExtension.newInstance(PackageVerificationExtension.java:36) ~[graph-data-science.jar:?]

	at com.neo4j.gds.configuration.PackageVerificationExtension.newInstance(PackageVerificationExtension.java:22) ~[graph-data-science.jar:?]

	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]

	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]

	... 5 more


```

**Comment by jmsuhy** [comment]
Could you please confirm which version of DozerDB you're using? 

Also, are you using the graph-data-science plugin we compiled or the one from the Neo4j GitHub repo? This will help us troubleshoot the issue.

Unfortunately, Neo4j's setup currently defaults to the commercial version of the graph-data-science plugin, even for the community edition. We may need to recompile the plugin for each Neo4j version if this continues.

Let me know your DozerDB version, and I'll figure out the next steps.

Thank you.

**Comment by lucifermorningstar1305** [comment]
Sure, I was using the dozerdb 5.20.0 alpha version. Well for the plugin, I downloaded and added the plugin to the `plugins` as mentioned in the README.md file and while starting the docker container I added `graph-data-science` aside from `apoc` into the `NEO4J_PLUGINS` list.

**Comment by lucifermorningstar1305** [comment]
Quick update: Got it fixed! 
Just simply removed the `"graph-data-science" ` from the `PLUGINS` array and added the downloaded `open-gds` plugin into the `plugins` and it started to work. Thanks for this amazing plugin! 
Also, I noticed that every version of this plugin is marked as alpha, therefore I was wondering if there are any plans to release a beta version of this?
