### ISSUE TITLE
OpenGDS Compiled version for neo4j 5.22.0

### ISSUE THREAD

**Issue by muddassir-lateef** [DozerDB/dozerdb-plugin#32]
As mentioned in the documentation of dozer db:

>If you would like to use the newest 2.8 alpha version of the graph data science plugin (called OpenGDS), you can download the version we compiled using the link below. It should work for Neo4j Core 5.16 and up. [Download OpenGDS 2.8.0-alpha01](https://dist.dozerdb.org/plugins/open-gds/open-gds-2.8.0-alpha01.jar) and place it in your $HOME/neo4j/plugins folder.
The graph data science plugin distributions available on Neo4j's website, through their GitHub repository, or via --env NEO4J_PLUGINS are only compatible with the Neo4j Enterprise Edition. See: [DozerDB Graph Data Science](https://github.com/DozerDB/graph-data-science).

I tried to use compiled version 2.8.0 mentioned here for neo4j 5.22.0 (i assume since the documentation is old it doesnot support the newer versions) and it gave me this error:

```
Caused by: java.lang.LinkageError: GDS 2.8.0-alpha01 is not compatible with Neo4j version: 5.22.0
	at org.neo4j.gds.compat.ProxyUtil$ProxyInfo.unsupported(ProxyUtil.java:247) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.compat.ProxyUtil.findProxy(ProxyUtil.java:54) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.compat.Neo4jProxy.<clinit>(Neo4jProxy.java:114) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:52) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:43) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]
	... 5 more
```
and the compatible gds version from neo4j also doesnot work as mentioned in the documentation . For ref when i try to use that it gives me the following error:

``` 
Caused by: java.lang.ClassNotFoundException: com.neo4j.metrics.MetricsManager
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.getMetricsRegister(GdsMetricsExtension.java:105) ~[neo4j-graph-data-science-2.10.1.jar:?]
	at com.neo4j.gds.metrics.GdsMetricsExtension$GdsMetricLifecycleAdapter.init(GdsMetricsExtension.java:78) ~[neo4j-graph-data-science-2.10.1.jar:?]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:72) ~[neo4j-kernel-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.22.0.jar:5.22.0]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:271) ~[neo4j-5.22.0.jar:5.22.0]
	... 5 more
```
I am running it with the following docker run command:
```
docker run -d \
    --memory=0\
    -p7474:7474 -p7687:7687 \
    -v $HOME/neo4j/data:/data \
    -v $HOME/neo4j/logs:/logs \
    -v $HOME/neo4j/import:/var/lib/neo4j/import \
    -v $HOME/neo4j/plugins:/plugins \
    --env NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD} \
    --env NEO4J_PLUGINS='["apoc"]' \
    --env NEO4J_apoc_export_file_enabled=true \
    --env NEO4J_apoc_import_file_enabled=true \
    --env NEO4J_dbms_security_procedures_unrestricted='*' \
    graphstack/dozerdb:5.22.0.0-alpha.1
```
The plugins directory for now only has apoc and the gds plugin.

Any help will be highly appreciated.

**Comment by jmsuhy** [comment]
It sounds like we may need to add building the OpenGDS library to our build script for each release.    We will start that with the upcoming 5.24.1 release.

**Comment by jmsuhy** [comment]
I just noticed that Neo4j now has release assets under the opengds project.   If they work, there is no need for us to compile this anymore.

Can you please verify if the newest version works with your DozerDb version?   We will test on the 5.24.1 release.  

https://github.com/neo4j/graph-data-science/releases

**Comment by jmsuhy** [comment]
<!DOCTYPE html><markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block;">Pulled from Neo4j GDS GitHub README.md Table 1. Compatibility matrix (italicized version is in development)
GDS version | Neo4j version | Java Version
-- | -- | --
GDS 2.12.x (preview) | Neo4j 5.25.0 | Java 21 & Java 17
Neo4j 5.24.0
Neo4j 5.23.0
GDS 2.11.x | Neo4j 5.24.0 | Java 21 & Java 17
Neo4j 5.23.0
GDS 2.10.x | Neo4j 5.24.0 | Java 21 & Java 17
Neo4j 5.23.0
Neo4j 5.22.0
GDS 2.9.x | Neo4j 5.23.0 | Java 21 & Java 17
Neo4j 5.22.0
Neo4j 5.21.0, 5.21.1, 5.21.2
Neo4j 5.20.0
Neo4j 5.19.0
Neo4j 5.18.0, 5.18.1
Neo4j 5.17.0
GDS 2.8.x | Neo4j 5.22.0 | Java 21 & Java 17
Neo4j 5.21.0, 5.21.1, 5.21.2
Neo4j 5.20.0
Neo4j 5.19.0
Neo4j 5.18.0, 5.18.1
Neo4j 5.17.0
Neo4j 5.16.0
GDS 2.7.x | Neo4j 5.21.0, 5.21.1, 5.21.2 | Java 21 & Java 17
Neo4j 5.20.0
Neo4j 5.19.0
Neo4j 5.18.0, 5.18.1
Neo4j 5.17.0
Neo4j 5.16.0
GDS 2.6.x | Neo4j 5.20.0 | Java 21 & Java 17
Neo4j 5.19.0
Neo4j 5.18.0, 5.18.1
Neo4j 5.17.0
Neo4j 5.16.0
Neo4j 5.15.0
Neo4j 5.14.0
Neo4j 4.4.9 - 4.4.37 | Java 11

</markdown-accessiblity-table><br class="Apple-interchange-newline">

**Comment by muddassir-lateef** [comment]
Thanks a lot for sharing @jmsuhy . Ill check it out today and let you know.

**Comment by muddassir-lateef** [comment]
@jmsuhy , I checked and https://github.com/neo4j/graph-data-science/releases/download/2.10.1/neo4j-graph-data-science-2.10.1.jar worked for me with neo4j 5.22.0 (2.8 and 2.9 didnot work even though they were mentioned to work with 5.22.0 in neo4j github readme). Thanks for the help.

**Comment by muddassir-lateef** [comment]
Hey @jmsuhy , None of the versions of open gds worked for this. Do you know what might be the issue. It is still giving me the same metricsmanager error.

PS Deleted the comment above to avoid misguiding someone because i did a noob mistake and  ran the image with the .zip file of gds in the plugins folder rather than the jar file in it.

Also when is the 5.24.1 release gonna come out? Is it possible to make it so that your ready made images have gds in it?

**Comment by b00134n** [comment]
@jmsuhy - I'm having a similar issue, with a slightly different error message. I just installed DozerDB as a docker image on a VPS with the command from the site. It spins up fine. However, if I download OpenGDS 2.8.0-alpha01 from the site link and add it to the /neo4j/plugins folder, I get the error below. This project is such a worthwhile OSS effort -- thanks for all your team's work on it. I really hope it's possible to get GDS working. :)

```
2024-11-14 06:31:36.414+0000 ERROR Failed to start Neo4j on 0.0.0.0:7474.
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:286) ~[neo4j-5.24.2.jar:5.24.2]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:221) ~[neo4j-5.24.2.jar:5.24.2]
	at org.neo4j.server.DozerDbBootstrapper.createNeo(DozerDbBootstrapper.java:46) ~[dozerdb-core-5.24.2-1.1.0-alpha.1.jar:5.24.2-1.1.0-alpha.1]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:185) [neo4j-5.24.2.jar:5.24.2-1.1.0-alpha.1]
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:100) [neo4j-5.24.2.jar:5.24.2-1.1.0-alpha.1]
	at org.neo4j.server.DozerDbEntryPoint.main(DozerDbEntryPoint.java:48) [dozerdb-core-5.24.2-1.1.0-alpha.1.jar:5.24.2-1.1.0-alpha.1]
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.GlobalExtensions@35f8a9d3' failed to initialize. Please see the attached cause exception "org.neo4j.internal.batchimport.Configuration".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:334) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:277) ~[neo4j-5.24.2.jar:5.24.2]
	... 5 more
Caused by: org.neo4j.kernel.extension.FailedToBuildExtensionException: Failed to build kernel extension Extension:OpenGraphDataScienceExtension[gds.open] because it is compiled with a reference to a class, method, or field, that is not in the class path: 'org/neo4j/internal/batchimport/Configuration'. The most common cause of this problem, is that Neo4j has been upgraded without also upgrading all installed extensions, such as APOC. Make sure that all of your extensions are build against your specific version of Neo4j.
	at org.neo4j.kernel.extension.ExtensionFailureStrategies.wrap(ExtensionFailureStrategies.java:56) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.extension.ExtensionFailureStrategies$1.handle(ExtensionFailureStrategies.java:68) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:68) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:277) ~[neo4j-5.24.2.jar:5.24.2]
	... 5 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/internal/batchimport/Configuration
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:52) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:43) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:277) ~[neo4j-5.24.2.jar:5.24.2]
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.internal.batchimport.Configuration
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.neo4j.gds.procedures.integration.LogAccessor.getLog(LogAccessor.java:33) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:52) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.gds.extension.OpenGraphDataScienceExtension.newInstance(OpenGraphDataScienceExtension.java:43) ~[open-gds-2.8.0-alpha01.jar:?]
	at org.neo4j.kernel.extension.AbstractExtensions.newInstance(AbstractExtensions.java:124) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.extension.AbstractExtensions.init(AbstractExtensions.java:62) ~[neo4j-kernel-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:317) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:56) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:85) ~[neo4j-common-5.24.2.jar:5.24.2]
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:277) ~[neo4j-5.24.2.jar:5.24.2]
```

**Comment by jmsuhy** [comment]
Ok, it sounds like we may have to also need to compile openGDS as part of our overall build process.  Just to confirm, did you download the version we compiled or did you test it on a version from Neo4j’s link below:

https://github.com/neo4j/graph-data-science/releases

**Comment by b00134n** [comment]
That would be awesome. The error happens after downloading the version you compiled.

**Comment by jmsuhy** [comment]
We just compiled version 2.12.0 of open-gds.   You can access it here:  https://dist.dozerdb.org/plugins/open-gds/open-gds-2.12.0.jar. - this will work for Neo4j Core / DozerDB 5.23+

We will setup a build process that will auto build these when they are tagged.   

If you are testing it - remember to remove the old version in your HOME/neo4j/plugins directory that is created when you run the docker version.

I have no idea why Neo4j made it open source, but only provided the commercial versions for download.  

Compiling is very straight forward.

**Comment by jmsuhy** [comment]
Did you still need the openGDS version for Neo4j 5.22.x core?  The one I pushed is for 5.23+

**Comment by b00134n** [comment]
Amazing. That fixed everything. I'm using the 5.24 Alpha build. After a little bit of pain getting SSL working (not specific to Dozer), I'm up and running. Thank you so much! 🤘

**Comment by jmsuhy** [comment]
If the GDS plugin works with Neo4j community then it will work with DozerDB with the same version number.
However - the issue with the parameters via the python driver is fixed in the upcoming 5.26 LTS release this month.
